import { Container } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { interSansFont, interTitleFont } from "./components/ui/fonts";
import { Navbar } from "./components/ui/Navbar";
import "./globals.css";
import { ThemeProvider } from "./theme/ThemeProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type RootLayoutProps = {
    readonly children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="es" className={`${interTitleFont.variable} ${interSansFont.variable}`}>
            <body className="antialiased">
                <AppRouterCacheProvider>
                    <ThemeProvider>
                        <Navbar />

                        <Container maxWidth="xl" sx={{ marginTop: "16px" }}>
                            {children}
                        </Container>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
