import type { Metadata } from "next";
import { interSansFont, interTitleFont } from "./components/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" className={`${interTitleFont.variable} ${interSansFont.variable}`}>
            <body className="antialiased">
                <header>NAVIGATION</header>
                {children}
            </body>
        </html>
    );
}
